general:
  seed: 20
  device: "cuda" 
  num_classes: 5
  class_names: ["EO", "IO", "LO", "PTE", "IPTE"]

paths:
  data_dir: "../data/structured/" 
  output_dir: "./outputs_debug"
  model_save_path: "./outputs_debug/best_model.pth"
  log_dir: "./logs_debug"
  eval_log_dir: "./logs_eval_debug"

training:
  model_type: "transfer"
  epochs: 100  
  batch_size: 8 
  learning_rate: 5e-4
  weight_decay: 1e-4
  scheduler: true
  step_size: 10
  gamma: 0.1
  early_stopping: false  
  patience: 3

dataset:
  img_size: 224        
  val_split: 0.2
  test_split: 0.1
  augmentations: true     

evaluate:
  model_path: "../outputs/best_model.pth"   
  log_dir: "./logs_eval_debug"

test: 
  output_res_path: "../test_outputs/"
  model_path: C:/Users/guill/Documents/github_projects/neuroflux-classification/src/outputs_debug/best_model.pth
  input_dir: "../data/raw/IO/"
  output_csv:  "../test/"
  model_type: "transfer"


     
